package optimizers

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"time"

	"github.com/lookatitude/beluga-ai/optimize"
	"github.com/lookatitude/beluga-ai/optimize/bayesian"
)

func init() {
	optimize.RegisterOptimizer("mipro", func(cfg optimize.OptimizerConfig) (optimize.Optimizer, error) {
		opts := []MIPROv2Option{}
		if cfg.LLM != nil {
			opts = append(opts, WithMIPROv2LLM(cfg.LLM))
		}
		return NewMIPROv2(opts...), nil
	})
}

// MIPROv2 implements Multi-step Instruction Proposal Optimization with Bayesian search.
//
// The algorithm jointly optimizes instructions and few-shot demonstrations using
// a Tree-structured Parzen Estimator (TPE) as the Bayesian backbone. When an
// LLMClient is provided, instruction candidates are generated by prompting the LLM
// with the program signature and training examples. Without an LLM, a set of
// diverse hand-crafted templates is used instead.
//
// The optimization loop proceeds as follows:
//  1. Proposal stage: generate NumInstructionCandidates instruction strings and
//     NumDemoCandidates shuffled demo sets from the trainset.
//  2. Bayesian search: for each of NumTrials trials, TPE samples (instruction_idx,
//     demo_idx) pairs, evaluating each candidate on a random minibatch. Scores feed
//     back into TPE so subsequent samples exploit high-scoring regions.
//  3. Convergence check: after each trial the rolling-window variance of recent
//     scores is tested; optimization stops early when variance < ConvergenceThreshold.
//  4. Validation scoring: if a valset is provided the final best candidate is
//     re-evaluated on it to provide an unbiased score.
//
// All RNG usage is race-safe: each trial allocates its own *rand.Rand seeded from
// seed XOR trial-index so results are deterministic yet goroutine-safe.
type MIPROv2 struct {
	// NumTrials is the number of Bayesian search trials to run.
	NumTrials int

	// MinibatchSize is the number of examples used per trial evaluation.
	MinibatchSize int

	// NumInstructionCandidates is the number of instruction variants to propose.
	NumInstructionCandidates int

	// NumDemoCandidates is the number of demonstration sets to propose.
	NumDemoCandidates int

	// NumDemosPerCandidate is the number of examples per demonstration set.
	NumDemosPerCandidate int

	// ConvergenceThreshold is the minimum score variance to continue optimization.
	ConvergenceThreshold float64

	// ConvergenceWindowSize is the rolling window length for variance computation.
	ConvergenceWindowSize int

	// LLM is an optional LLM client used for instruction proposal.
	// When nil, hard-coded template variants are used.
	LLM optimize.LLMClient

	// TPE is the Bayesian sampler; exposed for advanced configuration.
	TPE *bayesian.TPE

	// Seed for reproducibility.
	Seed int64
}

// MIPROv2Option configures a MIPROv2 optimizer.
type MIPROv2Option func(*MIPROv2)

// NewMIPROv2 creates a new MIPROv2 optimizer with sensible defaults.
func NewMIPROv2(opts ...MIPROv2Option) *MIPROv2 {
	m := &MIPROv2{
		NumTrials:                30,
		MinibatchSize:            25,
		NumInstructionCandidates: 5,
		NumDemoCandidates:        5,
		NumDemosPerCandidate:     4,
		ConvergenceThreshold:     0.001,
		ConvergenceWindowSize:    5,
		TPE:                      bayesian.NewTPE(),
		Seed:                     42,
	}
	for _, opt := range opts {
		opt(m)
	}
	m.TPE.WithSeed(m.Seed)
	return m
}

// WithNumTrials sets the number of Bayesian optimization trials.
func WithNumTrials(n int) MIPROv2Option {
	return func(m *MIPROv2) {
		if n > 0 {
			m.NumTrials = n
		}
	}
}

// WithMinibatchSize sets the evaluation minibatch size.
func WithMinibatchSize(n int) MIPROv2Option {
	return func(m *MIPROv2) {
		if n > 0 {
			m.MinibatchSize = n
		}
	}
}

// WithNumInstructionCandidates sets the number of instruction candidates proposed.
func WithNumInstructionCandidates(n int) MIPROv2Option {
	return func(m *MIPROv2) {
		if n > 0 {
			m.NumInstructionCandidates = n
		}
	}
}

// WithNumDemoCandidates sets the number of demonstration set candidates proposed.
func WithNumDemoCandidates(n int) MIPROv2Option {
	return func(m *MIPROv2) {
		if n > 0 {
			m.NumDemoCandidates = n
		}
	}
}

// WithNumDemosPerCandidate sets how many examples are included in each demo set.
func WithNumDemosPerCandidate(n int) MIPROv2Option {
	return func(m *MIPROv2) {
		if n > 0 {
			m.NumDemosPerCandidate = n
		}
	}
}

// WithMIPROv2Seed sets the random seed for deterministic results.
func WithMIPROv2Seed(seed int64) MIPROv2Option {
	return func(m *MIPROv2) {
		m.Seed = seed
	}
}

// WithMIPROv2LLM sets the LLM client used for instruction proposal.
func WithMIPROv2LLM(llm optimize.LLMClient) MIPROv2Option {
	return func(m *MIPROv2) {
		m.LLM = llm
	}
}

// WithMIPROv2Gamma sets the TPE gamma quantile (fraction of trials considered "good").
func WithMIPROv2Gamma(gamma float64) MIPROv2Option {
	return func(m *MIPROv2) {
		if gamma > 0 && gamma < 1 {
			m.TPE.WithGamma(gamma)
		}
	}
}

// WithMIPROv2ConvergenceThreshold sets the variance threshold for early stopping.
func WithMIPROv2ConvergenceThreshold(threshold float64) MIPROv2Option {
	return func(m *MIPROv2) {
		if threshold > 0 {
			m.ConvergenceThreshold = threshold
		}
	}
}

// WithMIPROv2ConvergenceWindow sets the rolling window size for convergence detection.
func WithMIPROv2ConvergenceWindow(n int) MIPROv2Option {
	return func(m *MIPROv2) {
		if n > 0 {
			m.ConvergenceWindowSize = n
		}
	}
}

// Compile implements optimize.Optimizer.
//
// It runs the full MIPROv2 multi-step optimization loop and returns an optimized
// program configured with the best-found instruction and demonstrations.
func (m *MIPROv2) Compile(ctx context.Context, program optimize.Program, opts optimize.CompileOptions) (optimize.Program, error) {
	if opts.Metric == nil {
		return nil, fmt.Errorf("mipro: metric is required")
	}
	if len(opts.Trainset) == 0 {
		return nil, fmt.Errorf("mipro: trainset is required")
	}

	// ── Phase 1: Proposal ──────────────────────────────────────────────────
	instructionCandidates, err := m.generateInstructionCandidates(ctx, program, opts)
	if err != nil {
		return nil, fmt.Errorf("mipro: instruction proposal failed: %w", err)
	}
	if len(instructionCandidates) == 0 {
		return nil, fmt.Errorf("mipro: no instruction candidates generated")
	}

	demoCandidates, err := m.generateDemoCandidates(ctx, program, opts)
	if err != nil {
		return nil, fmt.Errorf("mipro: demo candidate generation failed: %w", err)
	}
	if len(demoCandidates) == 0 {
		return nil, fmt.Errorf("mipro: no demo candidates generated")
	}

	// ── Phase 2: Bayesian search ───────────────────────────────────────────
	bestScore := -1.0
	var bestCandidate optimize.Candidate

	var bayesianTrials []bayesian.Trial

	convergence := &optimize.ConvergenceChecker{
		WindowSize: m.ConvergenceWindowSize,
		Threshold:  m.ConvergenceThreshold,
	}

	startTime := time.Now()

	for trial := 0; trial < m.NumTrials; trial++ {
		// Check context cancellation before each trial.
		select {
		case <-ctx.Done():
			if bestScore >= 0 {
				break
			}
			return nil, ctx.Err()
		default:
		}

		// Sample indices via TPE. Each call is guarded by TPE's internal mutex
		// (the TPE.Rand field is a value, not shared concurrently here).
		instructionIdx := m.TPE.SampleInt("instruction_idx", 0, len(instructionCandidates)-1, bayesianTrials)
		demoIdx := m.TPE.SampleInt("demo_idx", 0, len(demoCandidates)-1, bayesianTrials)

		candidate := optimize.Candidate{
			ID: fmt.Sprintf("trial_%d", trial),
			Prompts: map[string]string{
				"instruction": instructionCandidates[instructionIdx],
			},
			Demos: map[string][]optimize.Example{
				"demos": demoCandidates[demoIdx],
			},
		}

		// Use a per-trial RNG derived from the global seed to avoid sharing
		// mutable state between potential future concurrent callers.
		trialRNG := rand.New(rand.NewSource(m.Seed ^ int64(trial)))
		score, err := m.evaluateCandidate(ctx, program, candidate, opts, trialRNG)
		if err != nil {
			continue
		}

		// Feed result back into TPE with the canonical "value" key so that
		// buildIntDistribution can locate it.
		bayesianTrials = append(bayesianTrials, bayesian.Trial{
			Params: map[string]interface{}{
				"instruction_idx": instructionIdx,
				"demo_idx":        demoIdx,
				// "value" must be the integer that was sampled for the
				// distribution being modelled; we use instruction_idx as
				// the primary search dimension.
				"value": instructionIdx,
			},
			Score: score,
		})

		if score > bestScore {
			bestScore = score
			bestCandidate = candidate
		}

		// Notify callbacks.
		trialResult := optimize.Trial{
			ID:        trial,
			Candidate: candidate,
			Score:     score,
			Duration:  time.Since(startTime).Milliseconds(),
		}
		for _, cb := range opts.Callbacks {
			cb.OnTrialComplete(trialResult)
		}

		// Early stopping when score variance collapses.
		if convergence.Update(score) {
			break
		}

		// Budget check (iteration count).
		if opts.MaxCost != nil && opts.MaxCost.Exceeded(0, 0, trial+1) {
			break
		}
	}

	if bestScore < 0 {
		return nil, fmt.Errorf("mipro: no valid candidate found during optimization")
	}

	// ── Phase 3: Validation ────────────────────────────────────────────────
	valScore := bestScore
	if len(opts.Valset) > 0 {
		valScore, _ = m.evaluateOnSet(ctx, program, bestCandidate, opts.Valset, opts.Metric)
	}

	// Notify final callbacks.
	finalResult := optimize.OptimizationResult{
		BestCandidate: bestCandidate,
		BestScore:     valScore,
		NumTrials:     len(bayesianTrials),
		Duration:      time.Since(startTime).Milliseconds(),
		AllTrials:     buildTrials(bayesianTrials),
	}
	for _, cb := range opts.Callbacks {
		cb.OnOptimizationComplete(finalResult)
	}

	// ── Return optimized program ───────────────────────────────────────────
	return program.WithDemos(bestCandidate.Demos["demos"]), nil
}

// generateInstructionCandidates produces NumInstructionCandidates instruction strings.
//
// When m.LLM is non-nil the LLM is prompted with the program's signature fields
// and up to three training examples to generate diverse, grounded variants.
// Otherwise a set of high-quality templates is returned, padded or trimmed to
// exactly NumInstructionCandidates entries.
func (m *MIPROv2) generateInstructionCandidates(ctx context.Context, program optimize.Program, opts optimize.CompileOptions) ([]string, error) {
	if m.LLM != nil {
		return m.proposeInstructionsViaLLM(ctx, program, opts)
	}
	return m.templateInstructionCandidates(), nil
}

// proposeInstructionsViaLLM calls the LLM to generate grounded instruction variants.
//
// The prompt describes the program's input/output signature and includes a few
// representative training examples so the LLM can tailor the instructions to the
// task. Each call requests a single instruction; up to NumInstructionCandidates
// calls are made with increasing temperature for diversity.
func (m *MIPROv2) proposeInstructionsViaLLM(ctx context.Context, program optimize.Program, opts optimize.CompileOptions) ([]string, error) {
	sig := program.GetSignature()

	// Build a textual description of the signature.
	var sigDesc strings.Builder
	if sig != nil {
		for _, f := range sig.GetInputFields() {
			fmt.Fprintf(&sigDesc, "  Input  %s (%s): %s\n", f.Name, f.Type, f.Description)
		}
		for _, f := range sig.GetOutputFields() {
			fmt.Fprintf(&sigDesc, "  Output %s (%s): %s\n", f.Name, f.Type, f.Description)
		}
	}

	// Include up to 3 training examples.
	var exampleDesc strings.Builder
	nExamples := 3
	if nExamples > len(opts.Trainset) {
		nExamples = len(opts.Trainset)
	}
	for i := 0; i < nExamples; i++ {
		ex := opts.Trainset[i]
		fmt.Fprintf(&exampleDesc, "Example %d:\n  Inputs: %v\n  Expected: %v\n", i+1, ex.Inputs, ex.Outputs)
	}

	candidates := make([]string, 0, m.NumInstructionCandidates)

	for i := 0; i < m.NumInstructionCandidates; i++ {
		// Vary temperature to encourage diversity across candidates.
		temperature := 0.3 + float64(i)*0.15
		if temperature > 1.0 {
			temperature = 1.0
		}

		prompt := fmt.Sprintf(
			"You are an expert prompt engineer. Write a single, concise system instruction (1-2 sentences) "+
				"for an AI program with the following signature:\n\n%s\n"+
				"Representative training examples:\n%s\n"+
				"Instruction variant %d of %d (be creative and diverse):\n",
			sigDesc.String(),
			exampleDesc.String(),
			i+1,
			m.NumInstructionCandidates,
		)

		instruction, err := m.LLM.Complete(ctx, prompt, optimize.CompletionOptions{
			Temperature: temperature,
			MaxTokens:   80,
		})
		if err != nil {
			// Fall back to template for this slot on LLM failure.
			templates := m.templateInstructionCandidates()
			candidates = append(candidates, templates[i%len(templates)])
			continue
		}

		instruction = strings.TrimSpace(instruction)
		if instruction == "" {
			templates := m.templateInstructionCandidates()
			candidates = append(candidates, templates[i%len(templates)])
			continue
		}
		candidates = append(candidates, instruction)
	}

	return candidates, nil
}

// templateInstructionCandidates returns a diverse set of hard-coded instruction
// templates trimmed or padded to NumInstructionCandidates.
func (m *MIPROv2) templateInstructionCandidates() []string {
	base := []string{
		"Answer the question based on the context provided.",
		"Provide a concise answer to the question using the given context.",
		"Based on the information provided, what is the answer?",
		"Using only the context, answer this question:",
		"Respond to the question with information from the context.",
		"Think step by step and answer the question:",
		"You are a helpful assistant. Answer accurately and briefly:",
		"Extract the answer directly from the context:",
		"Given the following context, provide a factual answer:",
		"Analyze the context and respond with the most accurate answer:",
	}

	n := m.NumInstructionCandidates
	if n <= len(base) {
		return base[:n]
	}

	// Pad with cycled variants if more candidates are requested.
	result := make([]string, n)
	copy(result, base)
	for i := len(base); i < n; i++ {
		result[i] = base[i%len(base)]
	}
	return result
}

// generateDemoCandidates produces NumDemoCandidates shuffled demo sets from the trainset.
// Each candidate set contains NumDemosPerCandidate examples.
func (m *MIPROv2) generateDemoCandidates(_ context.Context, _ optimize.Program, opts optimize.CompileOptions) ([][]optimize.Example, error) {
	n := m.NumDemosPerCandidate

	candidates := make([][]optimize.Example, 0, m.NumDemoCandidates)
	for i := 0; i < m.NumDemoCandidates; i++ {
		// Per-candidate RNG so demo sets are deterministic but diverse.
		rng := rand.New(rand.NewSource(m.Seed + int64(i)))

		shuffled := make([]optimize.Example, len(opts.Trainset))
		copy(shuffled, opts.Trainset)
		rng.Shuffle(len(shuffled), func(a, b int) {
			shuffled[a], shuffled[b] = shuffled[b], shuffled[a]
		})

		end := n
		if end > len(shuffled) {
			end = len(shuffled)
		}
		candidates = append(candidates, shuffled[:end])
	}

	return candidates, nil
}

// evaluateCandidate scores a single candidate on a random minibatch from the trainset.
// The rng parameter must be a freshly created *rand.Rand unique to this trial.
func (m *MIPROv2) evaluateCandidate(ctx context.Context, program optimize.Program, candidate optimize.Candidate, opts optimize.CompileOptions, rng *rand.Rand) (float64, error) {
	minibatch := sampleMinibatch(opts.Trainset, m.MinibatchSize, rng)
	return m.evaluateOnSet(ctx, program, candidate, minibatch, opts.Metric)
}

// evaluateOnSet scores a candidate against the supplied example set.
func (m *MIPROv2) evaluateOnSet(ctx context.Context, program optimize.Program, candidate optimize.Candidate, examples []optimize.Example, metric optimize.Metric) (float64, error) {
	demos := candidate.Demos["demos"]
	prog := program.WithDemos(demos)

	var total float64
	var count int

	for _, ex := range examples {
		// Honour context cancellation mid-evaluation.
		select {
		case <-ctx.Done():
			if count > 0 {
				return total / float64(count), nil
			}
			return 0, ctx.Err()
		default:
		}

		pred, err := prog.Run(ctx, ex.Inputs)
		if err != nil {
			continue
		}

		score, err := metric.Evaluate(ex, pred, nil)
		if err != nil {
			continue
		}

		total += score
		count++
	}

	if count == 0 {
		return 0.0, nil
	}
	return total / float64(count), nil
}

// sampleMinibatch draws up to n examples from trainset using Fisher-Yates partial
// shuffle. It allocates its own slice so the caller's trainset is never mutated.
func sampleMinibatch(trainset []optimize.Example, n int, rng *rand.Rand) []optimize.Example {
	if n >= len(trainset) {
		cp := make([]optimize.Example, len(trainset))
		copy(cp, trainset)
		return cp
	}

	indices := make([]int, len(trainset))
	for i := range indices {
		indices[i] = i
	}
	for i := 0; i < n; i++ {
		j := i + rng.Intn(len(indices)-i)
		indices[i], indices[j] = indices[j], indices[i]
	}

	batch := make([]optimize.Example, n)
	for i := 0; i < n; i++ {
		batch[i] = trainset[indices[i]]
	}
	return batch
}

// buildTrials converts bayesian.Trial records to optimize.Trial records for callbacks.
func buildTrials(bt []bayesian.Trial) []optimize.Trial {
	trials := make([]optimize.Trial, len(bt))
	for i, t := range bt {
		trials[i] = optimize.Trial{
			ID:    i,
			Score: t.Score,
		}
	}
	return trials
}
