# golangci-lint v2 configuration for Beluga AI Framework
# Comprehensive linting setup for production-ready Go framework

version: "2"

run:
  # Timeout for analysis
  timeout: 5m
  
  # Include test files in linting
  tests: true

linters:
  # Enable comprehensive set of linters
  enable:
    # Error checking
    - errcheck
    - errorlint
    - errname
    
    # Security
    - gosec
    
    # Code quality
    - govet
    - staticcheck
    - gocritic
    - revive
    - ineffassign
    - unused
    - unparam
    - unconvert
    
    # Style
    - misspell
    - goconst
    
    # Complexity
    - gocyclo
    - funlen
    - lll
    
    # Duplication
    - dupl
    
    # Documentation
    - godot
    - godox
    
    # Performance
    - prealloc
    - makezero
    
    # Best practices
    - exhaustive
    - forbidigo
    - nolintlint
    - contextcheck
    - containedctx
    - importas
    - nakedret
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - wastedassign

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  max-same-issues: 50
