# golangci-lint v2 configuration for Beluga AI Framework
# Comprehensive linting setup for production-ready Go framework
# Based on best practices from Fiber, Gin, and other major Go frameworks

version: "2"

run:
  # Timeout for analysis
  timeout: 5m
  
  # Include test files in linting
  tests: true
  
  # Modules download mode
  modules-download-mode: readonly
  
  # Allow serial runners for consistency
  allow-serial-runners: true

linters:
  # Comprehensive set of linters based on industry best practices
  enable:
    # Error checking
    - errcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - nilerr
    - nilnil
    
    # Security
    - gosec
    
    # Code quality
    - govet
    - staticcheck
    - gocritic
    - revive
    - ineffassign
    - unused
    - unparam
    - unconvert
    - wastedassign
    
    # Style and formatting
    - asciicheck
    - bidichk
    - misspell
    - goconst
    - dupword
    - whitespace
    
    # Complexity
    - gocyclo
    - funlen
    - lll
    
    # Duplication
    - dupl
    
    # Documentation
    - godot
    - godox
    
    # Performance
    - prealloc
    - makezero
    - perfsprint
    
    # Best practices
    - exhaustive
    - forbidigo
    - nolintlint
    - contextcheck
    - containedctx
    - importas
    - nakedret
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - dogsled
    - durationcheck
    - forcetypeassert
    - gochecksumtype
    - goprintffuncname
    - musttag
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - reassign
    - testableexamples
    - tparallel
    - usestdlibvars
    - wrapcheck
    
    # HTTP and API
    - bodyclose
    
    # Testing
    - ginkgolinter
    - testifylint
    
    # Logging
    - loggercheck
    - sloglint
    - zerologlint
    
    # Dependencies
    - depguard
    - gomoddirectives
    
    # Import organization
    - grouper
    - decorder
    
    # Code organization
    - copyloopvar
    - mirror
    
    # Prometheus metrics
    - promlinter
    
    # Protocol buffers
    - protogetter
    
    # OpenTelemetry
    - spancheck
    
    # JSON/YAML
    - tagliatelle
    
  settings:
    # Dependency guard - restrict usage of certain packages
    depguard:
      rules:
        all:
          list-mode: lax
          deny:
            - pkg: flag
              desc: "`flag` package is only allowed in main.go"
            - pkg: log
              desc: "logging is provided by structured logging packages"
            - pkg: io/ioutil
              desc: "`io/ioutil` package is deprecated, use the `io` and `os` package instead"
    
    # Error checking configuration
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*bytes.Buffer).Write
        - (*github.com/valyala/bytebufferpool.ByteBuffer).Write
        - (*github.com/valyala/bytebufferpool.ByteBuffer).WriteByte
        - (*github.com/valyala/bytebufferpool.ByteBuffer).WriteString
    
    errchkjson:
      report-no-exported: true
    
    exhaustive:
      default-signifies-exhaustive: true
    
    # Forbid certain patterns
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^fmt\.Print(f|ln)?$
        - pattern: ^http\.Default(Client|ServeMux|Transport)$
      analyze-types: true
    
    goconst:
      numbers: true
      min-len: 3
    
    # Go Critic - advanced code analysis
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: false
        underef:
          skipRecvDeref: false
    
    # Security scanner configuration
    gosec:
      excludes:
        - G104  # Allow errors to be ignored if explicitly handled
        - G115  # Allow deferring file.Close() when using os.ReadFile
      config:
        global:
          audit: true
    
    # Go vet - enable all checks
    govet:
      enable-all: true
    
    # Import grouping
    grouper:
      import-require-single-import: true
      import-require-grouping: true
    
    # Logger check - ensure structured logging
    loggercheck:
      require-string-key: true
      no-printf-like: true
    
    misspell:
      locale: US
    
    # Nolint lint - require explanations
    nolintlint:
      require-explanation: true
      require-specific: true
    
    nonamedreturns:
      report-error-in-defer: true
    
    # Performance print - use better alternatives
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    
    predeclared:
      qualified-name: true
    
    # Prometheus metrics linting
    promlinter:
      strict: true
    
    # Revive - comprehensive linting rules
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-results
          disabled: true
        - name: comment-spacings
          arguments:
            - nolint
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: enforce-slice-style
          arguments:
            - make
          disabled: true
        - name: exported
          disabled: true
        - name: file-header
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: optimize-operands-order
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: unhandled-error
          disabled: true
    
    # Staticcheck - comprehensive static analysis
    staticcheck:
      checks:
        - all
        - -ST1000  # Package comment should be of the form
        - -ST1020  # The comment of exported function should start with function name
        - -ST1021  # The comment of exported type should start with type name
        - -ST1022  # The comment of exported variable should start with variable name
    
    # JSON/YAML tag naming
    tagliatelle:
      case:
        rules:
          json: snake
    
    # Testify linting
    testifylint:
      enable-all: true
    
    # Unused code detection
    unused:
      field-writes-are-uses: true
      exported-fields-are-used: true
    
    unparam:
      check-exported: false
    
    # Use standard library variables
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: false
      time-month: false
      time-layout: false
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    
    # Wrap check - ensure errors are wrapped
    wrapcheck:
      ignore-package-globs:
        - github.com/lookatitude/beluga-ai/*
        - errors
        - fmt
        - go.opentelemetry.io/otel/metric
        - go.opentelemetry.io/otel/trace
        - context

# Formatters configuration
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lookatitude/beluga-ai)
        - blank
        - dot
      custom-order: false
    gofumpt:
      module-path: github.com/lookatitude/beluga-ai
      extra-rules: true
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
# Issues configuration
issues:
  # Set to 0 to ensure all issues are addressed
  max-issues-per-linter: 0
  max-same-issues: 0
  # Disable govet (including printf) for react package to avoid panic bug in golangci-lint v2.6.2
  # Bug: interface conversion: types.Object is nil, not *types.Var in printf analyzer
  # when analyzing range loops - panic happens during analysis phase, not reporting
  exclude-rules:
    - path: pkg/agents/providers/react
      linters:
        - govet
        - errcheck
        - staticcheck
        - gosec
        - revive
        - gocritic
        - err113
        - errname
        - errorlint
        - nilerr
        - nilnil
        - ineffassign
        - unused
        - unparam
        - unconvert
        - wastedassign
        - asciicheck
        - bidichk
        - misspell
        - goconst
        - dupword
        - whitespace
        - gocyclo
        - funlen
        - lll
        - dupl
        - godot
        - godox
        - exhaustive
        - forbidigo
        - nolintlint
        - contextcheck
        - containedctx
        - importas
        - nakedret
        - noctx
        - rowserrcheck
        - sqlclosecheck
        - thelper
        - dogsled
        - durationcheck
        - forcetypeassert
        - gochecksumtype
        - goprintffuncname
        - musttag
        - nonamedreturns
        - nosprintfhostport
        - predeclared
        - reassign
        - testableexamples
        - tparallel
        - usestdlibvars
        - wrapcheck
        - bodyclose
        - ginkgolinter
        - testifylint
        - loggercheck
        - sloglint
        - zerologlint
        - depguard
        - gomoddirectives
        - grouper
        - decorder
        - copyloopvar
        - mirror
        - promlinter
        - protogetter
        - spancheck
        - tagliatelle
    # Exclude spancheck warnings for span helper functions that return spans for caller management
    - path: pkg/.*/metrics\.go
      text: "span is unassigned, probable memory leak"
      linters:
        - spancheck
    - path: pkg/llms/tracing\.go
      text: "span.End is not called on all paths"
      linters:
        - spancheck
    # Exclude containedctx for mock files - context storage is acceptable in mocks
    - path: .*/mock/.*\.go
      linters:
        - containedctx
    # Exclude containedctx for test files - context storage is acceptable in tests
    - path: .*_test\.go
      linters:
        - containedctx
    # Exclude containedctx for streaming providers - context storage is necessary for long-lived connections
    - path: pkg/voice/stt/providers/.*/streaming\.go
      linters:
        - containedctx
    - path: pkg/voice/stt/providers/.*/websocket\.go
      linters:
        - containedctx
    # Exclude containedctx for schedulers - context storage is necessary for worker lifecycle management
    - path: pkg/orchestration/internal/scheduler/.*\.go
      linters:
        - containedctx
    # Exclude containedctx for base agent - context is part of agent lifecycle
    - path: pkg/agents/internal/base/agent\.go
      linters:
        - containedctx
    # Exclude containedctx for monitoring errors - context is part of error context
    - path: pkg/monitoring/iface/errors\.go
      linters:
        - containedctx