package optimizer

import (
	"context"
	"fmt"
	"iter"
	"math/rand"
	"sync"
	"time"

	"github.com/lookatitude/beluga-ai/agent"
	"github.com/lookatitude/beluga-ai/tool"
)

// bootstrapFewShotConfig holds configuration for BootstrapFewShot.
type bootstrapFewShotConfig struct {
	// MaxBootstrapped is the max number of bootstrapped (teacher-generated) demos.
	MaxBootstrapped int
	// MaxLabeled is the max number of labeled (ground-truth) demos.
	MaxLabeled int
	// MaxRounds is the number of bootstrap attempts per training example.
	MaxRounds int
	// MetricThreshold is the minimum metric score to accept a demo.
	MetricThreshold float64
	// Teacher is an optional separate agent used for bootstrapping.
	// If nil, the student agent is used as its own teacher.
	Teacher agent.Agent
}

// BootstrapFewShotOption configures a BootstrapFewShot optimizer.
type BootstrapFewShotOption func(*bootstrapFewShotConfig)

// WithBootstrapTeacher sets the teacher agent used during bootstrapping.
// If unset, the student agent serves as its own teacher.
func WithBootstrapTeacher(teacher agent.Agent) BootstrapFewShotOption {
	return func(c *bootstrapFewShotConfig) {
		c.Teacher = teacher
	}
}

// WithBootstrapMaxBootstrapped sets the maximum number of bootstrapped demos.
// Bootstrapped demos are generated by running the teacher on training examples.
func WithBootstrapMaxBootstrapped(n int) BootstrapFewShotOption {
	return func(c *bootstrapFewShotConfig) {
		if n > 0 {
			c.MaxBootstrapped = n
		}
	}
}

// WithBootstrapMaxLabeled sets the maximum number of labeled demos.
// Labeled demos are drawn directly from the training set when bootstrapping fails.
func WithBootstrapMaxLabeled(n int) BootstrapFewShotOption {
	return func(c *bootstrapFewShotConfig) {
		if n > 0 {
			c.MaxLabeled = n
		}
	}
}

// WithBootstrapMaxRounds sets the number of bootstrap attempts per example.
func WithBootstrapMaxRounds(n int) BootstrapFewShotOption {
	return func(c *bootstrapFewShotConfig) {
		if n > 0 {
			c.MaxRounds = n
		}
	}
}

// WithBootstrapMetricThreshold sets the minimum score to accept a bootstrapped demo.
func WithBootstrapMetricThreshold(threshold float64) BootstrapFewShotOption {
	return func(c *bootstrapFewShotConfig) {
		if threshold >= 0 {
			c.MetricThreshold = threshold
		}
	}
}

// bootstrapFewShotOptimizer implements Optimizer using the BootstrapFewShot algorithm.
//
// The algorithm:
//  1. Run the teacher agent on each training example to produce predictions.
//  2. Score each prediction against the expected output using the metric.
//  3. Keep predictions that score above MetricThreshold as "bootstrapped demos".
//  4. Fill remaining demo slots with labeled examples from the training set.
//  5. Return the student agent wrapped with the selected demonstrations.
//
// The resulting agent has demonstrations injected into its persona backstory,
// improving few-shot performance without modifying the underlying LLM weights.
type bootstrapFewShotOptimizer struct {
	cfg  bootstrapFewShotConfig
	seed int64
}

// newBootstrapFewShotOptimizer creates a BootstrapFewShot optimizer.
func newBootstrapFewShotOptimizer(seed int64, extra map[string]any, opts ...BootstrapFewShotOption) *bootstrapFewShotOptimizer {
	cfg := bootstrapFewShotConfig{
		MaxBootstrapped: 4,
		MaxLabeled:      16,
		MaxRounds:       1,
		MetricThreshold: 1.0,
	}
	for _, opt := range opts {
		opt(&cfg)
	}
	// Allow extra map to override defaults (used by registry)
	if v, ok := extra["max_bootstrapped"].(int); ok && v > 0 {
		cfg.MaxBootstrapped = v
	}
	if v, ok := extra["max_labeled"].(int); ok && v > 0 {
		cfg.MaxLabeled = v
	}
	if v, ok := extra["max_rounds"].(int); ok && v > 0 {
		cfg.MaxRounds = v
	}
	if v, ok := extra["metric_threshold"].(float64); ok && v >= 0 {
		cfg.MetricThreshold = v
	}
	return &bootstrapFewShotOptimizer{cfg: cfg, seed: seed}
}

// agentPrediction wraps a result from an agent invocation.
type agentPrediction struct {
	text  string
	score float64
}

// Optimize implements the Optimizer interface.
func (b *bootstrapFewShotOptimizer) Optimize(
	ctx context.Context,
	agt agent.Agent,
	opts OptimizeOptions,
) (*Result, error) {
	if opts.Metric == nil {
		return nil, fmt.Errorf("optimizer: bootstrapfewshot: metric is required")
	}
	if len(opts.Trainset.Examples) == 0 {
		return nil, fmt.Errorf("optimizer: bootstrapfewshot: trainset is required")
	}

	teacher := b.cfg.Teacher
	if teacher == nil {
		teacher = agt
	}

	// Seed deterministic randomness for demo selection.
	seed := b.seed
	if seed == 0 {
		seed = time.Now().UnixNano()
	}
	rng := rand.New(rand.NewSource(seed)) //nolint:gosec

	startTime := now()
	var (
		trials    []Trial
		trialsMu  sync.Mutex
		totalCost float64
		trialID   int
	)

	// Phase 1: Bootstrap demonstrations from the teacher.
	bootstrapped := make([]Example, 0, b.cfg.MaxBootstrapped)
	for _, ex := range opts.Trainset.Examples {
		if len(bootstrapped) >= b.cfg.MaxBootstrapped {
			break
		}

		for round := 0; round < b.cfg.MaxRounds; round++ {
			trialStart := now()

			// Invoke teacher.
			input := buildInput(ex)
			output, err := teacher.Invoke(ctx, input)

			pred := Prediction{Text: output}
			score := 0.0
			var trialErr error

			if err != nil {
				trialErr = err
			} else {
				score, trialErr = opts.Metric.Score(ctx, ex, pred)
			}

			trialsMu.Lock()
			t := Trial{
				ID:       trialID,
				Score:    score,
				Duration: now().Sub(trialStart),
				Error:    trialErr,
				Config: TrialConfig{
					Prompts: map[string]string{"input": input},
					Demos:   map[string][]Example{"bootstrapped": append([]Example{}, bootstrapped...)},
				},
			}
			trials = append(trials, t)
			trialID++
			trialsMu.Unlock()

			// Notify trial callbacks.
			for _, cb := range opts.Callbacks {
				cb.OnTrialComplete(ctx, t)
			}

			if trialErr == nil && score >= b.cfg.MetricThreshold {
				// Accept this as a bootstrapped demo.
				demo := Example{
					Inputs:   ex.Inputs,
					Outputs:  map[string]any{"output": output, "answer": output},
					Metadata: ex.Metadata,
				}
				bootstrapped = append(bootstrapped, demo)
				break
			}
		}

		// Respect budget: check both IsExceeded (cost/calls/duration) and MaxIterations.
		elapsed := now().Sub(startTime)
		if opts.Budget.IsExceeded(totalCost, trialID, elapsed) {
			break
		}
		if opts.Budget.MaxIterations > 0 && trialID >= opts.Budget.MaxIterations {
			break
		}
	}

	// Phase 2: Fill remaining slots with labeled examples.
	labeled := make([]Example, 0, b.cfg.MaxLabeled)
	maxLabeled := b.cfg.MaxLabeled

	// Shuffle training examples for variety before picking labeled demos.
	shuffled := make([]Example, len(opts.Trainset.Examples))
	copy(shuffled, opts.Trainset.Examples)
	rng.Shuffle(len(shuffled), func(i, j int) {
		shuffled[i], shuffled[j] = shuffled[j], shuffled[i]
	})

	for _, ex := range shuffled {
		if len(labeled) >= maxLabeled {
			break
		}
		if !containsBootstrapExample(bootstrapped, ex) {
			labeled = append(labeled, ex)
		}
	}

	// Combine: bootstrapped first, then labeled, up to total cap.
	cap := b.cfg.MaxBootstrapped + b.cfg.MaxLabeled
	demos := make([]Example, 0, cap)
	demos = append(demos, bootstrapped...)
	for _, l := range labeled {
		if len(demos) >= cap {
			break
		}
		demos = append(demos, l)
	}

	// Build the best trial for reporting.
	bestScore := 0.0
	bestID := 0
	for _, t := range trials {
		if t.Score > bestScore {
			bestScore = t.Score
			bestID = t.ID
		}
	}

	// Return a WrappedAgent that injects the demos into its persona at call time.
	wrapped := newDemoAgent(agt, demos)

	result := &Result{
		Agent:             wrapped,
		Score:             bestScore,
		Trials:            trials,
		TotalCost:         totalCost,
		TotalDuration:     now().Sub(startTime),
		BestTrial:         bestID,
		ConvergenceStatus: ConvergenceReached,
	}
	if len(trials) == 0 || bestScore < b.cfg.MetricThreshold {
		result.ConvergenceStatus = ConvergenceNotReached
	}

	return result, nil
}

// buildInput converts an Example's Inputs to a single string for the agent.
func buildInput(ex Example) string {
	if v, ok := ex.Inputs["input"].(string); ok {
		return v
	}
	if v, ok := ex.Inputs["question"].(string); ok {
		return v
	}
	// Fall back to concatenating all inputs.
	result := ""
	for k, v := range ex.Inputs {
		if result != "" {
			result += "\n"
		}
		result += fmt.Sprintf("%s: %v", k, v)
	}
	return result
}

// containsBootstrapExample checks whether a demo is already in the list using input equality.
func containsBootstrapExample(demos []Example, ex Example) bool {
	for _, d := range demos {
		if bootstrapExamplesEqual(d, ex) {
			return true
		}
	}
	return false
}

// bootstrapExamplesEqual reports whether two examples have equivalent inputs.
func bootstrapExamplesEqual(a, b Example) bool {
	if len(a.Inputs) != len(b.Inputs) {
		return false
	}
	for k, v := range a.Inputs {
		if b.Inputs[k] != v {
			return false
		}
	}
	return true
}

// demoAgent wraps an agent.Agent and injects few-shot demonstrations
// into every Invoke/Stream call via persona augmentation.
type demoAgent struct {
	mu    sync.RWMutex
	base  agent.Agent
	demos []Example
}

func newDemoAgent(base agent.Agent, demos []Example) *demoAgent {
	return &demoAgent{base: base, demos: demos}
}

// ID returns the base agent ID with a "-bootstrapped" suffix.
func (d *demoAgent) ID() string { return d.base.ID() + "-bootstrapped" }

// Persona returns the original persona.
func (d *demoAgent) Persona() agent.Persona { return d.base.Persona() }

// Tools forwards to the base agent.
func (d *demoAgent) Tools() []tool.Tool { return d.base.Tools() }

// Children forwards to the base agent.
func (d *demoAgent) Children() []agent.Agent { return d.base.Children() }

// Invoke executes the base agent with the few-shot demos injected.
func (d *demoAgent) Invoke(ctx context.Context, input string, opts ...agent.Option) (string, error) {
	d.mu.RLock()
	demos := d.demos
	d.mu.RUnlock()

	fullInput := buildDemoPrompt(input, demos)
	return d.base.Invoke(ctx, fullInput, opts...)
}

// Stream executes the base agent and returns a streaming iterator.
func (d *demoAgent) Stream(ctx context.Context, input string, opts ...agent.Option) iter.Seq2[agent.Event, error] {
	d.mu.RLock()
	demos := d.demos
	d.mu.RUnlock()

	fullInput := buildDemoPrompt(input, demos)
	return d.base.Stream(ctx, fullInput, opts...)
}

// Demos returns the current set of few-shot demonstrations.
func (d *demoAgent) Demos() []Example {
	d.mu.RLock()
	defer d.mu.RUnlock()
	cp := make([]Example, len(d.demos))
	copy(cp, d.demos)
	return cp
}

// buildDemoPrompt prepends few-shot demonstrations to the input string.
func buildDemoPrompt(input string, demos []Example) string {
	if len(demos) == 0 {
		return input
	}

	var buf []byte
	buf = append(buf, "Here are some examples:\n\n"...)
	for i, demo := range demos {
		buf = fmt.Appendf(buf, "Example %d:\n", i+1)
		if q, ok := demo.Inputs["input"].(string); ok {
			buf = fmt.Appendf(buf, "Input: %s\n", q)
		} else if q, ok := demo.Inputs["question"].(string); ok {
			buf = fmt.Appendf(buf, "Input: %s\n", q)
		}
		if a, ok := demo.Outputs["answer"].(string); ok {
			buf = fmt.Appendf(buf, "Output: %s\n", a)
		} else if a, ok := demo.Outputs["output"].(string); ok {
			buf = fmt.Appendf(buf, "Output: %s\n", a)
		}
		buf = append(buf, '\n')
	}
	buf = append(buf, "Now answer the following:\n"...)
	buf = append(buf, input...)
	return string(buf)
}
