// Command provider-catalog walks the Beluga AI provider directories and emits
// a Markdown catalog to stdout. The output is meant to be redirected into
// docs/reference/providers.md and checked for drift via `make docs-providers`.
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// category describes one provider directory to scan.
type category struct {
	// Label is the human-readable section heading.
	Label string
	// Path is the directory relative to the repo root (e.g. "llm/providers").
	Path string
}

// categories lists every provider-style directory in the tree. Keep this list
// sorted by layer (L1 → L6) so the output reads naturally.
var categories = []category{
	// Layer 1 — Foundation
	{Label: "Observability", Path: "o11y/providers"},
	// Layer 2 — Cross-cutting
	{Label: "State stores", Path: "state/providers"},
	{Label: "Workflow engines", Path: "workflow/providers"},
	// Layer 3 — Capability
	{Label: "LLM", Path: "llm/providers"},
	{Label: "Embedding", Path: "rag/embedding/providers"},
	{Label: "Vector stores", Path: "rag/vectorstore/providers"},
	{Label: "Document loaders", Path: "rag/loader/providers"},
	{Label: "Memory stores", Path: "memory/stores"},
	{Label: "Guard", Path: "guard/providers"},
	{Label: "Prompt", Path: "prompt/providers"},
	{Label: "Eval", Path: "eval/providers"},
	{Label: "Cache", Path: "cache/providers"},
	{Label: "STT (speech-to-text)", Path: "voice/stt/providers"},
	{Label: "TTS (text-to-speech)", Path: "voice/tts/providers"},
	{Label: "S2S (speech-to-speech)", Path: "voice/s2s/providers"},
	{Label: "Voice transport", Path: "voice/transport/providers"},
	{Label: "VAD (voice activity detection)", Path: "voice/vad/providers"},
	// Layer 4 — Protocol
	{Label: "MCP", Path: "protocol/mcp/providers"},
	{Label: "Server adapters", Path: "server/adapters"},
}

func main() {
	root := repoRoot()

	fmt.Println("<!-- GENERATED by internal/tools/provider-catalog — do not hand-edit -->")
	fmt.Println("<!-- Intro prose and Related links are embedded in the tool source (internal/tools/provider-catalog/main.go); provider tables are filesystem-derived. -->")
	fmt.Println("<!-- Regenerate: go run ./internal/tools/provider-catalog > docs/reference/providers.md -->")
	fmt.Println()
	fmt.Println("# Reference: Providers")
	fmt.Println()
	fmt.Println("Every extensible package in Beluga follows the same registry model: a provider implements a small interface (1-4 methods), registers itself via `init()`, and becomes available at runtime through `Register` / `New` / `List`. Import a provider's package for its side-effect (`import _ \"github.com/lookatitude/beluga-ai/llm/providers/openai\"`) and call `llm.New(\"openai\", cfg)` to get a fully wired instance with middleware, hooks, and tracing attached.")
	fmt.Println()
	fmt.Println("To add your own provider to any category below, follow the [Provider Template](../patterns/provider-template.md) pattern and the step-by-step [Custom Provider guide](../guides/custom-provider.md). The five-part recipe (implement the interface, write a factory, register in `init()`, write table-driven tests, document in godoc) applies identically to every category listed here.")
	fmt.Println()
	fmt.Println("The counts below reflect the actual directory tree. If a provider directory exists, it appears here. If it doesn't, it won't. To regenerate this file after adding a provider, run `go run ./internal/tools/provider-catalog > docs/reference/providers.md`.")
	fmt.Println()

	totalProviders := 0
	totalCategories := 0

	for _, cat := range categories {
		dir := filepath.Join(root, cat.Path)
		providers, err := listProviders(dir)
		if err != nil {
			// Directory does not exist — skip silently.
			continue
		}
		if len(providers) == 0 {
			continue
		}
		totalCategories++
		totalProviders += len(providers)

		fmt.Printf("## %s — `%s`\n\n", cat.Label, cat.Path)
		fmt.Println("| Provider | Description |")
		fmt.Println("|---|---|")
		for _, p := range providers {
			desc := readDocSentence(filepath.Join(dir, p))
			fmt.Printf("| `%s` | %s |\n", p, desc)
		}
		fmt.Printf("\n**Count:** %d\n\n", len(providers))
	}

	fmt.Printf("---\n\n**Total providers:** %d across %d categories.\n", totalProviders, totalCategories)
	fmt.Println()
	fmt.Println("## Related")
	fmt.Println()
	fmt.Println("- [Extensibility Patterns](../architecture/03-extensibility-patterns.md) -- the four mechanisms (interface, registry, hooks, middleware) every provider uses.")
	fmt.Println("- [Registry + Factory pattern](../patterns/registry-factory.md) -- the registration model in detail.")
	fmt.Println("- [Provider Template](../patterns/provider-template.md) -- building a new provider end-to-end.")
	fmt.Println("- [Custom Provider guide](../guides/custom-provider.md) -- step-by-step walkthrough.")
}

// repoRoot returns the repository root by walking up from the executable (or
// the current working directory) looking for go.mod.
func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		fatal("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fatal("could not find go.mod in any parent directory")
		}
		dir = parent
	}
}

// listProviders returns sorted subdirectory names inside dir.
func listProviders(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		// Skip internal helpers (e.g. memory/stores/internal).
		if e.Name() == "internal" || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)
	return names, nil
}

// readDocSentence reads doc.go in dir and returns the first sentence of the
// package comment. Falls back to a placeholder if doc.go is missing or empty.
func readDocSentence(dir string) string {
	path := filepath.Join(dir, "doc.go")
	f, err := os.Open(filepath.Clean(path))
	if err != nil {
		return "_(no doc.go)_"
	}
	defer f.Close()

	commentLines := collectCommentLines(f)

	if len(commentLines) == 0 {
		return "_(no doc.go)_"
	}

	// Join the comment lines and extract the first sentence.
	text := strings.Join(commentLines, " ")
	text = strings.TrimSpace(text)

	// First sentence ends at the first ". " or ".\n" (or end of text).
	if idx := strings.Index(text, ". "); idx >= 0 {
		return text[:idx+1]
	}
	// Might end with just a period.
	if strings.HasSuffix(text, ".") {
		return text
	}
	// No period at all — return the whole first paragraph.
	return text
}

// collectCommentLines reads Go // comment lines from f, stopping at the first
// non-comment line after at least one comment has been seen.
func collectCommentLines(f *os.File) []string {
	var lines []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		switch {
		case strings.HasPrefix(line, "// "):
			lines = append(lines, strings.TrimPrefix(line, "// "))
		case strings.HasPrefix(line, "//"):
			lines = append(lines, "")
		default:
			if len(lines) > 0 {
				return lines
			}
		}
	}
	return lines
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "provider-catalog: "+format+"\n", args...)
	os.Exit(1)
}
