// Package main is the entry point for the sample Beluga AI
// project. It was generated by `beluga init sample` on
// 2026-04-20T00:00:00Z and follows the canonical Layer 7 consumer shape
// described in framework/docs/architecture/01-overview.md.
//
// To swap providers, replace the blank import below with one of:
//
//	_ "github.com/lookatitude/beluga-ai/v2/llm/providers/anthropic"
//	_ "github.com/lookatitude/beluga-ai/v2/llm/providers/ollama"
//	_ "github.com/lookatitude/beluga-ai/v2/llm/providers/google"
//
// and update the provider name / model in the llm.New call below. See
// framework/docs/reference/providers.md for the full list.
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/lookatitude/beluga-ai/v2/agent"
	"github.com/lookatitude/beluga-ai/v2/config"
	"github.com/lookatitude/beluga-ai/v2/core"
	"github.com/lookatitude/beluga-ai/v2/llm"
	"github.com/lookatitude/beluga-ai/v2/tool"

	// Register the openai provider via init().
	_ "github.com/lookatitude/beluga-ai/v2/llm/providers/openai"
)

// EchoInput is the typed input for the echo tool. Struct tags drive the
// generated JSON Schema so the LLM sees a well-formed tool contract.
type EchoInput struct {
	Message string `json:"message" description:"The message to echo back verbatim" required:"true"`
}

// newEchoTool returns a minimal tool demonstrating registration + dispatch
// + round-trip. The LLM will call this tool when the user prompt asks for
// an echo; the persona's backstory nudges it in that direction.
func newEchoTool() tool.Tool {
	return tool.NewFuncTool(
		"echo",
		"Echo the provided message back verbatim. Use this to demonstrate tool invocation.",
		func(ctx context.Context, in EchoInput) (*tool.Result, error) {
			if in.Message == "" {
				return nil, core.Errorf(core.ErrInvalidInput, "echo: message is required")
			}
			return tool.TextResult(in.Message), nil
		},
	)
}

func main() {
	apiKey := os.Getenv("OPENAI_API_KEY")
	if apiKey == "" {
		log.Fatal("OPENAI_API_KEY is not set.\n" +
			"  Get a key at https://platform.openai.com/api-keys\n" +
			"  Or swap providers: see the comments at the top of this file.")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	model, err := llm.New("openai", config.ProviderConfig{
		Provider: "openai",
		APIKey:   apiKey,
		Model:    "gpt-4o-mini",
	})
	if err != nil {
		log.Fatalf("llm.New: %v", err)
	}

	a := agent.New("sample-agent",
		agent.WithLLM(model),
		agent.WithPersona(agent.Persona{
			Role:      "helpful assistant",
			Goal:      "answer questions accurately",
			Backstory: "You are concise and direct. When asked to echo something, always use the echo tool.",
			Traits:    []string{"concise", "accurate"},
		}),
		agent.WithTools([]tool.Tool{newEchoTool()}),
		// agent.WithPlannerName("reflexion"), // see: docs/architecture/06-reasoning-strategies.md
	)

	answer, err := a.Invoke(ctx, "Please echo: hello world")
	if err != nil {
		log.Fatalf("agent.Invoke: %v", err)
	}

	fmt.Println(answer)
}
