package schema

import "strings"

// Role represents the role of a message sender in a conversation.
type Role string

const (
	// RoleSystem identifies a system-level instruction message.
	RoleSystem Role = "system"
	// RoleHuman identifies a message from a human user.
	RoleHuman Role = "human"
	// RoleAI identifies a message generated by an AI model.
	RoleAI Role = "ai"
	// RoleTool identifies a message containing a tool execution result.
	RoleTool Role = "tool"
)

// Message is the interface implemented by all message types in a conversation.
// Messages carry multimodal content parts and optional metadata.
type Message interface {
	// GetRole returns the role of the message sender.
	GetRole() Role
	// GetContent returns the content parts that make up this message.
	GetContent() []ContentPart
	// GetMetadata returns arbitrary metadata associated with this message.
	GetMetadata() map[string]any
}

// Usage tracks token consumption for an AI model response.
type Usage struct {
	// InputTokens is the number of tokens in the input/prompt.
	InputTokens int
	// OutputTokens is the number of tokens in the generated output.
	OutputTokens int
	// TotalTokens is the total token count (input + output).
	TotalTokens int
	// CachedTokens is the number of tokens served from cache.
	CachedTokens int
}

// SystemMessage represents a system-level instruction message that sets
// the behavior and context for the AI model.
type SystemMessage struct {
	// Parts contains the multimodal content of this message.
	Parts []ContentPart
	// Metadata holds arbitrary key-value pairs associated with this message.
	Metadata map[string]any
}

// GetRole returns RoleSystem.
func (m *SystemMessage) GetRole() Role { return RoleSystem }

// GetContent returns the message's content parts.
func (m *SystemMessage) GetContent() []ContentPart { return m.Parts }

// GetMetadata returns the message's metadata.
func (m *SystemMessage) GetMetadata() map[string]any { return m.Metadata }

// Text extracts and concatenates all text content from the message's parts.
func (m *SystemMessage) Text() string { return extractText(m.Parts) }

// HumanMessage represents a message from a human user.
type HumanMessage struct {
	// Parts contains the multimodal content of this message.
	Parts []ContentPart
	// Metadata holds arbitrary key-value pairs associated with this message.
	Metadata map[string]any
}

// GetRole returns RoleHuman.
func (m *HumanMessage) GetRole() Role { return RoleHuman }

// GetContent returns the message's content parts.
func (m *HumanMessage) GetContent() []ContentPart { return m.Parts }

// GetMetadata returns the message's metadata.
func (m *HumanMessage) GetMetadata() map[string]any { return m.Metadata }

// Text extracts and concatenates all text content from the message's parts.
func (m *HumanMessage) Text() string { return extractText(m.Parts) }

// AIMessage represents a message generated by an AI model, including
// any tool calls the model wants to make and token usage statistics.
type AIMessage struct {
	// Parts contains the multimodal content of this message.
	Parts []ContentPart
	// ToolCalls contains any tool invocations requested by the model.
	ToolCalls []ToolCall
	// Usage tracks token consumption for this response.
	Usage Usage
	// ModelID identifies the model that generated this message.
	ModelID string
	// Metadata holds arbitrary key-value pairs associated with this message.
	Metadata map[string]any
}

// GetRole returns RoleAI.
func (m *AIMessage) GetRole() Role { return RoleAI }

// GetContent returns the message's content parts.
func (m *AIMessage) GetContent() []ContentPart { return m.Parts }

// GetMetadata returns the message's metadata.
func (m *AIMessage) GetMetadata() map[string]any { return m.Metadata }

// Text extracts and concatenates all text content from the message's parts.
func (m *AIMessage) Text() string { return extractText(m.Parts) }

// ToolMessage represents the result of a tool execution, sent back to the
// model to inform it of the tool's output.
type ToolMessage struct {
	// ToolCallID is the ID of the ToolCall this message responds to.
	ToolCallID string
	// Parts contains the multimodal content of the tool result.
	Parts []ContentPart
	// Metadata holds arbitrary key-value pairs associated with this message.
	Metadata map[string]any
}

// GetRole returns RoleTool.
func (m *ToolMessage) GetRole() Role { return RoleTool }

// GetContent returns the message's content parts.
func (m *ToolMessage) GetContent() []ContentPart { return m.Parts }

// GetMetadata returns the message's metadata.
func (m *ToolMessage) GetMetadata() map[string]any { return m.Metadata }

// Text extracts and concatenates all text content from the message's parts.
func (m *ToolMessage) Text() string { return extractText(m.Parts) }

// NewSystemMessage creates a new SystemMessage with a single text content part.
func NewSystemMessage(text string) *SystemMessage {
	return &SystemMessage{
		Parts: []ContentPart{TextPart{Text: text}},
	}
}

// NewHumanMessage creates a new HumanMessage with a single text content part.
func NewHumanMessage(text string) *HumanMessage {
	return &HumanMessage{
		Parts: []ContentPart{TextPart{Text: text}},
	}
}

// NewAIMessage creates a new AIMessage with a single text content part.
func NewAIMessage(text string) *AIMessage {
	return &AIMessage{
		Parts: []ContentPart{TextPart{Text: text}},
	}
}

// NewToolMessage creates a new ToolMessage with a single text content part
// and the given tool call ID.
func NewToolMessage(callID, text string) *ToolMessage {
	return &ToolMessage{
		ToolCallID: callID,
		Parts:      []ContentPart{TextPart{Text: text}},
	}
}

// extractText concatenates all TextPart values from the given content parts.
func extractText(parts []ContentPart) string {
	var b strings.Builder
	for i, p := range parts {
		if tp, ok := p.(TextPart); ok {
			if i > 0 && b.Len() > 0 {
				b.WriteByte('\n')
			}
			b.WriteString(tp.Text)
		}
	}
	return b.String()
}
